// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Employee struct {
	EmployeeID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	JoiningDate time.Time
	Salary      string
	PanNumber   string
	Year        int32
	TaxIncome   string
	Deductions  sql.NullString
	Designation string
}
